name: All Coverage
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
        - runtime
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  all-coverage:
    name: All Coverage
    runs-on:
      group: github-v1
    environment:
      name: github-pages
      url: ${{ steps.pages-deploy.outputs.page_url }}
    env:
      CC: clang
      EXTRAS: llvm-cov
    steps:
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y llvm lcov

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/deps

      - name: Build unit tests
        run: make -j -Otarget unit-test

      - uses: ./.github/actions/hugepages

      - name: Run Unit Tests
        run: |
          sudo prlimit --pid $$ --memlock=-1:-1
          ./test.sh -j --page-sz gigantic

      - name: Make Test Coverage Report
        run: |
          make cov-report
          mkdir -p build/pages/
          mv build/native/clang/cov/html build/pages/cov

      - name: Drop an Index
        run: |
          cat <<EOS > build/pages/index.html
          <!DOCTYPE html>
          <html>
          <head>
          <title>🔥💃 Pages</title>
          </head>

          <body>
          <h1>🔥💃 Pages</h1>
          <h2>Links 🔗</h2>
          <ul>
          <li><a href="./cov/">Test Coverage</li>
          </ul>
          </body>

          </html>
          EOS

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: './build/pages/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
