name: On Pull Request
on:
  push:
    branches: [runtime]
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
