name: test-tvu.sh & test-tvu-load.sh
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
jobs:
  tests:
    runs-on: private
    env:
      CC: gcc
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/deps
      - uses: ./.github/actions/hugepages

      - name: build
        run: |
          ./contrib/make-j fddev all

      - name: test-tvu.sh
        run: |
          sudo prlimit --pid=$$ --nofile=1048576
          sudo prlimit --pid=$$ --memlock=unlimited
          ./test-tvu.sh

      - name: test-tvu-load.sh
        run: |
          sudo prlimit --pid=$$ --nofile=1048576
          sudo prlimit --pid=$$ --memlock=unlimited
          ./test-tvu-load.sh

      - name: test-tvu-fddev.sh
        run: |
          sudo prlimit --pid=$$ --nofile=1048576
          sudo prlimit --pid=$$ --memlock=unlimited
          ./test-tvu-fddev.sh
